// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/animateList.vue')['default']
    Breadcrumb: typeof import('./../src/components/breadcrumb.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    HdHistoryLink: typeof import('./../src/components/hd/HistoryLink.vue')['default']
    HdMenu: typeof import('./../src/components/hd/Menu.vue')['default']
    HdNavBar: typeof import('./../src/components/hd/NavBar.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MarkdownMarkdowneditor: typeof import('./../src/components/markdown/markdowneditor.vue')['default']
    Notification: typeof import('./../src/components/notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditorWangeditor: typeof import('./../src/components/wangEditor/wangeditor.vue')['default']
  }
}

export {}
