// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHistoryLink: typeof import('./../src/components/admin/HistoryLink.vue')['default']
    AdminMenu: typeof import('./../src/components/admin/Menu.vue')['default']
    AdminNavBar: typeof import('./../src/components/admin/NavBar.vue')['default']
    AdminNavbarBreadcrumb: typeof import('./../src/components/admin/navbar/Breadcrumb.vue')['default']
    AdminNavbarFullScreen: typeof import('./../src/components/admin/navbar/FullScreen.vue')['default']
    AdminNavbarThemeSetting: typeof import('./../src/components/admin/navbar/ThemeSetting.vue')['default']
    AdminNavbarUserInfo: typeof import('./../src/components/admin/navbar/UserInfo.vue')['default']
    AdminQuickBar: typeof import('./../src/components/admin/QuickBar.vue')['default']
    AnimateList: typeof import('./../src/components/animateList.vue')['default']
    Dialog: typeof import('./../src/components/dialog.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    FormArticle: typeof import('./../src/components/form/article.vue')['default']
    FormList: typeof import('./../src/components/form/list.vue')['default']
    FormLogin: typeof import('./../src/components/form/login.vue')['default']
    HdCard: typeof import('./../src/components/hd/card.vue')['default']
    HdFooter: typeof import('./../src/components/hd/footer.vue')['default']
    HdHome: typeof import('./../src/components/hd/home.vue')['default']
    HdIndroduce: typeof import('./../src/components/hd/indroduce.vue')['default']
    HdPhoto: typeof import('./../src/components/hd/photo.vue')['default']
    IconArrowUp: typeof import('@icon-park/vue-next')['ArrowUp']
    IconGoEnd: typeof import('@icon-park/vue-next')['GoEnd']
    IconGoStart: typeof import('@icon-park/vue-next')['GoStart']
    IconLeft: typeof import('@icon-park/vue-next')['Left']
    IconMindmapList: typeof import('@icon-park/vue-next')['MindmapList']
    IconPause: typeof import('@icon-park/vue-next')['Pause']
    IconPlayCycle: typeof import('@icon-park/vue-next')['PlayCycle']
    IconPlayOne: typeof import('@icon-park/vue-next')['PlayOne']
    IconShuffleOne: typeof import('@icon-park/vue-next')['ShuffleOne']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    MemberInfo: typeof import('./../src/components/member/info.vue')['default']
    MemberPassword: typeof import('./../src/components/member/password.vue')['default']
    MusicContainer: typeof import('./../src/components/music/container.vue')['default']
    Notification: typeof import('./../src/components/notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableList: typeof import('./../src/components/table/list.vue')['default']
    TablePagination: typeof import('./../src/components/table/pagination.vue')['default']
    TableSearch: typeof import('./../src/components/table/search.vue')['default']
    UploadImg: typeof import('./../src/components/uploadImg.vue')['default']
    WangEditor: typeof import('./../src/components/wang/editor.vue')['default']
  }
}

export {}
